// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyZ1WVrRWr98KaH4OA-LYSKmeS0U8rcZ8',
    appId: '1:999323139941:web:efb80e07d97d97afa92b8c',
    messagingSenderId: '999323139941',
    projectId: 'lumasdang',
    authDomain: 'lumasdang.firebaseapp.com',
    storageBucket: 'lumasdang.firebasestorage.app',
    measurementId: 'G-2RMC2QWS81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOiNXTxWxhoCV0tWmnO_bSiVQJSZW3JoY',
    appId: '1:999323139941:android:e464d8a3a41eb780a92b8c',
    messagingSenderId: '999323139941',
    projectId: 'lumasdang',
    storageBucket: 'lumasdang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf0wr1nTDavsQS53IXx54il01rL0OYVsA',
    appId: '1:999323139941:ios:89333ff78d05257ba92b8c',
    messagingSenderId: '999323139941',
    projectId: 'lumasdang',
    storageBucket: 'lumasdang.firebasestorage.app',
    iosBundleId: 'com.example.lumasdang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf0wr1nTDavsQS53IXx54il01rL0OYVsA',
    appId: '1:999323139941:ios:89333ff78d05257ba92b8c',
    messagingSenderId: '999323139941',
    projectId: 'lumasdang',
    storageBucket: 'lumasdang.firebasestorage.app',
    iosBundleId: 'com.example.lumasdang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyZ1WVrRWr98KaH4OA-LYSKmeS0U8rcZ8',
    appId: '1:999323139941:web:3e46a3c40f3329a5a92b8c',
    messagingSenderId: '999323139941',
    projectId: 'lumasdang',
    authDomain: 'lumasdang.firebaseapp.com',
    storageBucket: 'lumasdang.firebasestorage.app',
    measurementId: 'G-7MH216414L',
  );
}
